-- Creación de usuarios CLIENTES
CREATE USER 'DCHICA'@'localhost' IDENTIFIED BY 'AK8LPEJ1M';
CREATE USER 'DSOLER'@'localhost' IDENTIFIED BY 'POO12M1AU';
CREATE USER 'JGIRALDO'@'localhost' IDENTIFIED BY 'SUPDM1NHP';
CREATE USER 'OGOMEZ'@'localhost' IDENTIFIED BY 'S1101TRA';
CREATE USER 'CGIMENEZ'@'localhost' IDENTIFIED BY 'SEM1EEBT9';
CREATE USER 'MSARMIENTO'@'localhost' IDENTIFIED BY 'SEHM9DMP5';
CREATE USER 'DRODRIGUEZ'@'localhost' IDENTIFIED BY 'SPDMP91JA';
CREATE USER 'ABECKER'@'localhost' IDENTIFIED BY 'SMADMQOMP';
CREATE USER 'VMARTINEZ'@'localhost' IDENTIFIED BY 'FPDLURS19';

-- Creación de usuarios CAJEROS
CREATE USER 'JVEGAS'@'localhost' IDENTIFIED BY 'FJ9ALSD19';
CREATE USER 'LSUARES'@'localhost' IDENTIFIED BY 'PLJ6SAJ19';
CREATE USER 'PLINARES'@'localhost' IDENTIFIED BY 'FKALS912';
CREATE USER 'NESCOBAR'@'localhost' IDENTIFIED BY 'PLAOSJ12';

-- Creación de usuario ADMINISTRADOR
CREATE USER 'CGONZALES'@'localhost' IDENTIFIED BY 'SUAOEIUSA';

-- Permisos para CLIENTES (solo lectura sobre sus datos y movimientos relacionados)
GRANT SELECT, UPDATE ON USUARIO TO 'DCHICA'@'localhost';
GRANT SELECT ON MOVIMIENTO TO 'DCHICA'@'localhost';
GRANT SELECT ON DETALLE_DEUDAS TO 'DCHICA'@'localhost';
GRANT SELECT ON DETALLE_VENTA TO 'DCHICA'@'localhost';

GRANT SELECT, UPDATE ON USUARIO TO 'DSOLER'@'localhost';
GRANT SELECT ON MOVIMIENTO TO 'DSOLER'@'localhost';
GRANT SELECT ON DETALLE_DEUDAS TO 'DSOLER'@'localhost';
GRANT SELECT ON DETALLE_VENTA TO 'DSOLER'@'localhost';

GRANT SELECT, UPDATE ON USUARIO TO 'JGIRALDO'@'localhost';
GRANT SELECT ON MOVIMIENTO TO 'JGIRALDO'@'localhost';
GRANT SELECT ON DETALLE_DEUDAS TO 'JGIRALDO'@'localhost';
GRANT SELECT ON DETALLE_VENTA TO 'JGIRALDO'@'localhost';

GRANT SELECT, UPDATE ON USUARIO TO 'OGOMEZ'@'localhost';
GRANT SELECT ON MOVIMIENTO TO 'OGOMEZ'@'localhost';
GRANT SELECT ON DETALLE_DEUDAS TO 'OGOMEZ'@'localhost';
GRANT SELECT ON DETALLE_VENTA TO 'OGOMEZ'@'localhost';

GRANT SELECT, UPDATE ON USUARIO TO 'CGIMENEZ'@'localhost';
GRANT SELECT ON MOVIMIENTO TO 'CGIMENEZ'@'localhost';
GRANT SELECT ON DETALLE_DEUDAS TO 'CGIMENEZ'@'localhost';
GRANT SELECT ON DETALLE_VENTA TO 'CGIMENEZ'@'localhost';

GRANT SELECT, UPDATE ON USUARIO TO 'MSARMIENTO'@'localhost';
GRANT SELECT ON MOVIMIENTO TO 'MSARMIENTO'@'localhost';
GRANT SELECT ON DETALLE_DEUDAS TO 'MSARMIENTO'@'localhost';
GRANT SELECT ON DETALLE_VENTA TO 'MSARMIENTO'@'localhost';

GRANT SELECT, UPDATE ON USUARIO TO 'DRODRIGUEZ'@'localhost';
GRANT SELECT ON MOVIMIENTO TO 'DRODRIGUEZ'@'localhost';
GRANT SELECT ON DETALLE_DEUDAS TO 'DRODRIGUEZ'@'localhost';
GRANT SELECT ON DETALLE_VENTA TO 'DRODRIGUEZ'@'localhost';

GRANT SELECT, UPDATE ON USUARIO TO 'ABECKER'@'localhost';
GRANT SELECT ON MOVIMIENTO TO 'ABECKER'@'localhost';
GRANT SELECT ON DETALLE_DEUDAS TO 'ABECKER'@'localhost';
GRANT SELECT ON DETALLE_VENTA TO 'ABECKER'@'localhost';

GRANT SELECT, UPDATE ON USUARIO TO 'VMARTINEZ'@'localhost';
GRANT SELECT ON MOVIMIENTO TO 'VMARTINEZ'@'localhost';
GRANT SELECT ON DETALLE_DEUDAS TO 'VMARTINEZ'@'localhost';
GRANT SELECT ON DETALLE_VENTA TO 'VMARTINEZ'@'localhost';

-- Permisos para CAJEROS (pueden registrar ventas, compras y actualizar usuarios)
GRANT SELECT, INSERT, UPDATE ON USUARIO TO 'JVEGAS'@'localhost';
GRANT SELECT, INSERT ON MOVIMIENTO TO 'JVEGAS'@'localhost';
GRANT SELECT, INSERT ON DETALLE_VENTA TO 'JVEGAS'@'localhost';
GRANT SELECT, INSERT ON DETALLE_COMPRA TO 'JVEGAS'@'localhost';

GRANT SELECT, INSERT, UPDATE ON USUARIO TO 'LSUARES'@'localhost';
GRANT SELECT, INSERT ON MOVIMIENTO TO 'LSUARES'@'localhost';
GRANT SELECT, INSERT ON DETALLE_VENTA TO 'LSUARES'@'localhost';
GRANT SELECT, INSERT ON DETALLE_COMPRA TO 'LSUARES'@'localhost';

GRANT SELECT, INSERT, UPDATE ON USUARIO TO 'PLINARES'@'localhost';
GRANT SELECT, INSERT ON MOVIMIENTO TO 'PLINARES'@'localhost';
GRANT SELECT, INSERT ON DETALLE_VENTA TO 'PLINARES'@'localhost';
GRANT SELECT, INSERT ON DETALLE_COMPRA TO 'PLINARES'@'localhost';

GRANT SELECT, INSERT, UPDATE ON USUARIO TO 'NESCOBAR'@'localhost';
GRANT SELECT, INSERT ON MOVIMIENTO TO 'NESCOBAR'@'localhost';
GRANT SELECT, INSERT ON DETALLE_VENTA TO 'NESCOBAR'@'localhost';
GRANT SELECT, INSERT ON DETALLE_COMPRA TO 'NESCOBAR'@'localhost';

-- Permisos para ADMINISTRADOR (todos los privilegios sobre toda la base)
GRANT ALL PRIVILEGES ON CONJUNTO.* TO 'CGONZALES'@'localhost';

-- Aplicar cambios
FLUSH PRIVILEGES;
