-- --------------------------------------- CREANDO USUARIOS
-- --------------------------------- CLIENTES
CREATE USER 'DCHICA'@'LOCALHOST' IDENTIFIED BY 'AK8LPEJ1M';
CREATE USER 'DSOLER'@'LOCALHOST' IDENTIFIED BY 'POO12M1AU';
CREATE USER 'JGIRALDO'@'LOCALHOST' IDENTIFIED BY 'SUPDM1NHP';
CREATE USER 'OGOMEZ'@'LOCALHOST' IDENTIFIED BY 'S1101TRA';
CREATE USER 'CGIMENEZ'@'LOCALHOST' IDENTIFIED BY 'SEM1EEBT9';
CREATE USER 'MSARMIENTO'@'LOCALHOST' IDENTIFIED BY 'SEHM9DMP5';
CREATE USER 'DRODRIGUEZ'@'LOCALHOST' IDENTIFIED BY 'SPDMP91JA';
CREATE USER 'ABECKER'@'LOCALHOST' IDENTIFIED BY 'SMADMQOMP';
CREATE USER 'VMARTINEZ'@'LOCALHOST' IDENTIFIED BY 'FPDLURS19';
-- --------------------------------- CAJEROS
CREATE USER 'JVEGAS'@'LOCALHOST'
IDENTIFIED BY 'FJ9ALSD19';
CREATE USER 'LSUARES'@'LOCALHOST'
IDENTIFIED BY 'PLJ6SAJ19';
CREATE USER 'PLINARES'@'LOCALHOST'
IDENTIFIED BY 'FKALS912';
CREATE USER 'NESCOBAR'@'LOCALHOST'
IDENTIFIED BY 'PLAOSJ12';
-- --------------------------------- ADMINISTRADOR
CREATE USER 'CGONZALES'@'LOCALHOST'
IDENTIFIED BY 'SUAOEIUSA';
-- --------------------------- DANDO PERMISOS
-- ----------------------- PRIVILEGIOS AL ADMIN
-- ----------------------- PRIVILEGIOS AL CLIENTE
-- 'DCHICA'
GRANT SELECT, UPDATE ON USUARIO TO 'DCHICA'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTA TO 'DCHICA'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTAS_CREDITO TO 'DCHICA'@'LOCALHOST';
-- 'DSOLER'
GRANT SELECT, UPDATE ON USUARIO TO 'DSOLER'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTA TO 'DSOLER'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTAS_CREDITO TO 'DSOLER'@'LOCALHOST';
-- 'JGIRALDO'
GRANT SELECT, UPDATE ON USUARIO TO 'JGIRALDO'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTA TO 'JGIRALDO'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTAS_CREDITO TO 'JGIRALDO'@'LOCALHOST';
-- 'OGOMEZ'
GRANT SELECT, UPDATE ON USUARIO TO 'OGOMEZ'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTA TO 'OGOMEZ'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTAS_CREDITO TO 'OGOMEZ'@'LOCALHOST';
-- 'CGIMENEZ'
GRANT SELECT, UPDATE ON USUARIO TO 'CGIMENEZ'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTA TO 'CGIMENEZ'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTAS_CREDITO TO 'CGIMENEZ'@'LOCALHOST';
-- 'MSARMIENTO'
GRANT SELECT, UPDATE ON USUARIO TO 'MSARMIENTO'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTA TO 'MSARMIENTO'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTAS_CREDITO TO 'MSARMIENTO'@'LOCALHOST';
-- 'DRODRIGUEZ'
GRANT SELECT, UPDATE ON USUARIO TO 'DRODRIGUEZ'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTA TO 'DRODRIGUEZ'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTAS_CREDITO TO 'DRODRIGUEZ'@'LOCALHOST';
-- 'ABECKER'
GRANT SELECT, UPDATE ON USUARIO TO 'ABECKER'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTA TO 'ABECKER'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTAS_CREDITO TO 'ABECKER'@'LOCALHOST';
-- 'VMARTINEZ'
GRANT SELECT, UPDATE ON USUARIO TO 'VMARTINEZ'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTA TO 'VMARTINEZ'@'LOCALHOST';
GRANT SELECT, UPDATE ON VENTAS_CREDITO TO 'VMARTINEZ'@'LOCALHOST';
-- -----------------------PRIVILEGIOS AL CAJERO
-- NESCOBAR
GRANT SELECT ON COMPRA TO 'NESCOBAR'@'LOCALHOST';
GRANT INSERT, SELECT ON VENTAS_CREDITO TO 'NESCOBAR'@'LOCALHOST';
GRANT INSERT, SELECT, UPDATE ON USUARIO TO 'NESCOBAR'@'LOCALHOST';
GRANT INSERT, SELECT ON VENTA TO 'NESCOBAR'@'LOCALHOST';
-- PLINARES
GRANT SELECT ON COMPRA TO 'PLINARES'@'LOCALHOST';
GRANT INSERT, SELECT ON VENTAS_CREDITO TO 'PLINARES'@'LOCALHOST';
GRANT INSERT, SELECT, UPDATE ON USUARIO TO 'PLINARES'@'LOCALHOST';
GRANT INSERT, SELECT ON VENTA TO 'PLINARES'@'LOCALHOST';
-- LSUARES
GRANT SELECT ON COMPRA TO 'LSUARES'@'LOCALHOST';
GRANT INSERT, SELECT ON VENTAS_CREDITO TO 'LSUARES'@'LOCALHOST';
GRANT INSERT, SELECT, UPDATE ON USUARIO TO 'LSUARES'@'LOCALHOST';
GRANT INSERT, SELECT ON VENTA TO 'LSUARES'@'LOCALHOST';
-- JVEGAS
GRANT SELECT ON COMPRA TO 'JVEGAS'@'LOCALHOST';
GRANT INSERT, SELECT ON VENTAS_CREDITO TO 'JVEGAS'@'LOCALHOST';
GRANT INSERT, SELECT, UPDATE ON USUARIO TO 'JVEGAS'@'LOCALHOST';
GRANT INSERT, SELECT ON VENTA TO 'JVEGAS'@'LOCALHOST';

SELECT USER, 'LOCALHOST' FROM mysql.user;