USE CONJUNTO;

DROP TRIGGER IF EXISTS Desactivar_Producto;

DELIMITER //
CREATE TRIGGER Desactivar_Producto
BEFORE UPDATE ON PRODUCTO
FOR EACH ROW 
BEGIN
    IF NEW.FECHA_VENCIMIENTO IS NOT NULL AND CURDATE() > NEW.FECHA_VENCIMIENTO THEN
        SET NEW.ESTADO_PRODUCTO = 'NO DISPONIBLE';
    END IF;
END;
//
DELIMITER ;
