CREATE VIEW vista_productos_con_usuario AS
SELECT 
    P.ID_PRODUCTO,
    P.NOMBRE_PRODUCTO,
    P.DESCRIPCION_PRODUCTO,
    P.CANTIDAD_DISPONIBLE,
    P.UNIDAD_MEDIDA,
    P.COSTO_UNITARIO,
    P.FECHA_ENTREGA,
    P.FECHA_VENCIMIENTO,
    U.CEDULA,
    CONCAT(U.NOMBRE, ' ', U.APELLIDO) AS REGISTRADO_POR
FROM PRODUCTO P
JOIN USUARIO U ON P.REGISTRADO_POR = U.CEDULA;

CREATE VIEW vista_compras_con_detalles AS
SELECT 
    DC.ID_COMPRA,
    M.FECHA_MOVIMIENTO,
    M.VALOR_MOVIMIENTO,
    DC.CANTIDAD_COMPRADA,
    P.NOMBRE_PRODUCTO,
    P.UNIDAD_MEDIDA
FROM DETALLE_COMPRA DC
JOIN MOVIMIENTO M ON DC.MOVIMIENTO = M.ID_MOVIMIENTO
JOIN PRODUCTO P ON DC.PRODUCTO_COMPRADO = P.ID_PRODUCTO;

CREATE VIEW vista_ventas_completas AS
SELECT 
    DV.ID_VENTA,
    M.FECHA_MOVIMIENTO,
    M.VALOR_MOVIMIENTO,
    M.ESTADO_MOVIMIENTO,
    CONCAT(U.NOMBRE, ' ', U.APELLIDO) AS CLIENTE,
    DV.CANTIDAD_VENDIDA,
    P.NOMBRE_PRODUCTO
FROM DETALLE_VENTA DV
JOIN MOVIMIENTO M ON DV.MOVIMIENTO = M.ID_MOVIMIENTO
JOIN PRODUCTO P ON DV.PRODUCTO_VENDIDO = P.ID_PRODUCTO
JOIN USUARIO U ON M.CLIENTE = U.CEDULA;

CREATE VIEW vista_deudas_con_detalles AS
SELECT 
    DD.ID_DEUDA,
    M.FECHA_MOVIMIENTO,
    DD.FECHA_VENCIMIENTO,
    DD.CANTIDAD_DEUDA,
    DD.SALDO,
    P.NOMBRE_PRODUCTO,
    CONCAT(U.NOMBRE, ' ', U.APELLIDO) AS CLIENTE
FROM DETALLE_DEUDAS DD
JOIN MOVIMIENTO M ON DD.MOVIMIENTO = M.ID_MOVIMIENTO
JOIN PRODUCTO P ON DD.PRODUCTO_PENDIENTE = P.ID_PRODUCTO
JOIN USUARIO U ON M.CLIENTE = U.CEDULA;