CREATE DATABASE CONJUNTO;
USE CONJUNTO;
#Drop database CONJUNTO;
CREATE TABLE USUARIO (
		CEDULA BIGINT UNSIGNED PRIMARY KEY,
		NOMBRE VARCHAR(25) NOT NULL,
        APELLIDO VARCHAR(25) NOT NULL,
        CONTRASENA VARCHAR(25) NOT NULL,
		CORREO VARCHAR(60) NOT NULL,
		TIPO_USUARIO ENUM('ADMINISTRADOR','CAJERO','CLIENTE') NOT NULL,
		ESTADO ENUM('ACTIVO','INACTIVO') DEFAULT 'ACTIVO' NOT NULL,
		TELEFONO INT UNSIGNED NOT NULL,
		GENERO ENUM('MASCULINO','FEMENINO') NOT NULL
	);
    CREATE TABLE PROVEEDOR (
		ID_PROVEEDOR INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
		NOMBRE_PROVEEDOR VARCHAR(25) NOT NULL,
		NUMERO_TELEFONICO BIGINT UNSIGNED NOT NULL,
        CORREO_PROVEEDOR VARCHAR(40) NOT NULL,
        DIRECCION VARCHAR(40) NOT NULL,
		ESTADO ENUM('ACTIVO','INACTIVO') DEFAULT 'ACTIVO' NOT NULL
	);
    CREATE TABLE INVENTARIO (
		ID_INVENTARIO TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
		NOMBRE_PRODUCTO VARCHAR(30) NOT NULL,
		DESCRIPCION_PRODUCTO VARCHAR(40) NOT NULL,
		CANTIDAD_DISPONIBLE TINYINT UNSIGNED NOT NULL,
        UNIDAD_MEDIDA ENUM('L','Ml','Gal','M','Cm','Ft','Kg','G','Lb','Mg') NOT NULL,
		ESTADO_PRODUCTO ENUM('DISPONIBLE','NO DISPONIBLE') DEFAULT 'DISPONIBLE' NOT NULL, 
		COSTO_UNITARIO SMALLINT UNSIGNED NOT NULL,
        FECHA_ENTREGA DATE NOT NULL,
        FECHA_VENCIMIENTO DATE NULL,
		REGISTRADO_POR BIGINT UNSIGNED NOT NULL,
		FOREIGN KEY (REGISTRADO_POR) REFERENCES USUARIO (CEDULA)
	);
    CREATE TABLE COMPRA (
		ID_COMPRA TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
		FECHA_COMPRA DATE NOT NULL,
		VALOR_COMPRA MEDIUMINT UNSIGNED NOT NULL,
		CANTIDAD_COMPRA TINYINT UNSIGNED NOT NULL,
		ESTADO_COMPRA ENUM('REALIZADA','NO REALIZADA') DEFAULT 'NO REALIZADA' NOT NULL,
		DESCUENTO INT UNSIGNED NULL,
		REGISTRADA_POR BIGINT UNSIGNED NOT NULL,
		SUMINISTRADA_POR INT UNSIGNED NOT NULL,
		FOREIGN KEY (REGISTRADA_POR) REFERENCES USUARIO (CEDULA),
		FOREIGN KEY (SUMINISTRADA_POR) REFERENCES PROVEEDOR (ID_PROVEEDOR)
	);
CREATE TABLE DETALLES_SURTE (
		ID_DETALLE_SURTE TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
		VALOR_PRODUCTO MEDIUMINT NOT NULL,
		CANTIDAD_PRODUCTO INT NOT NULL,
		COMPRA TINYINT UNSIGNED NOT NULL,
		INVENTARIO TINYINT UNSIGNED NOT NULL,
		FOREIGN KEY (COMPRA) REFERENCES COMPRA (ID_COMPRA),
		FOREIGN KEY (INVENTARIO) REFERENCES INVENTARIO (ID_INVENTARIO)
	);
CREATE TABLE DETALLES_SUMINISTRA (
		ID_DETALLE_SUMINISTRA TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
		PROVEEDOR INT UNSIGNED NOT NULL,
		INVENTARIO TINYINT UNSIGNED NOT NULL,
		FOREIGN KEY (PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR),
		FOREIGN KEY (INVENTARIO) REFERENCES INVENTARIO (ID_INVENTARIO)
	);
CREATE TABLE VENTA(
       ID_VENTA TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
       FECHA_SALIDA DATE NOT NULL,
       TOTAL_PAGAR INT UNSIGNED NOT NULL,
       ESTADO_VENTA ENUM('REALIZADA','PENDIENTE') NOT NULL,
       VENTA_REALIZADA_POR BIGINT UNSIGNED NOT NULL,
       DESCUENTO_POR_EVENTO TINYINT UNSIGNED NOT NULL,
       FOREIGN KEY (DESCUENTO_POR_EVENTO) REFERENCES EVENTO (ID_EVENTO),
       FOREIGN KEY (VENTA_REALIZADA_POR) REFERENCES USUARIO (CEDULA)
    );
CREATE TABLE DETALLES_VENTA (
		ID_DETALLE_VENTA TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
        CANTIDAD_PRODUCTO TINYINT UNSIGNED NOT NULL,
		VALOR_TOTAL MEDIUMINT UNSIGNED NOT NULL,
		INVENTARIO TINYINT UNSIGNED NOT NULL,
		VENTA TINYINT UNSIGNED NOT NULL,
		FOREIGN KEY (INVENTARIO) REFERENCES INVENTARIO (ID_INVENTARIO),
		FOREIGN KEY (VENTA) REFERENCES VENTA (ID_VENTA)
	);
CREATE TABLE EVENTO( 
	   ID_EVENTO TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
       NOMBRE_EVENTO VARCHAR(100) NOT NULL,
       DESCRIPCION_EVENTO VARCHAR(100) NOT NULL,
       TIPO_EVENTO VARCHAR(30) NOT NULL,
       FECHA_EVENTO DATE NOT NULL,
       HORA_INICIO TIME NOT NULL,
       HORA_FIN TIME NOT NULL,
       LUGAR VARCHAR(30) NOT NULL,
       OBSERVACIONES VARCHAR(50) NOT NULL,
       DESCUENTO TINYINT NULL
    );
CREATE TABLE DETALLE_SURTE_EVENTO (
    CANTIDAD_PRODUCTO TINYINT UNSIGNED NOT NULL,
	VALOR_PRODUCTO MEDIUMINT UNSIGNED NOT NULL,
    INVENTARIO TINYINT UNSIGNED NOT NULL,
	EVENTO TINYINT UNSIGNED NOT NULL,
	FOREIGN KEY (INVENTARIO) REFERENCES INVENTARIO (ID_INVENTARIO),
	FOREIGN KEY (EVENTO) REFERENCES EVENTO (ID_EVENTO)
    );
CREATE TABLE VENTAS_CREDITO (
    ID_FIADO TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	SALDO INT UNSIGNED NOT NULL,
    NUMERO_CUOTAS TINYINT UNSIGNED NOT NULL,
    FECHA_PAGO_CUOTA DATE NOT NULL,
    FECHA_FIADO DATE NOT NULL,
	DEUDA_DE BIGINT UNSIGNED NOT NULL,
    DE_QUE_VENTA_ES TINYINT UNSIGNED NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
	FOREIGN KEY (DEUDA_DE) REFERENCES USUARIO (CEDULA),
    FOREIGN KEY (DE_QUE_VENTA_ES) REFERENCES VENTA (ID_VENTA)
    );