CREATE DATABASE CONJUNTO;
USE CONJUNTO;
#Drop database CONJUNTO;
CREATE TABLE USUARIO (
	CEDULA BIGINT UNSIGNED PRIMARY KEY,
	NOMBRE VARCHAR(25) NOT NULL,
	APELLIDO VARCHAR(25) NOT NULL,
	CLAVE VARCHAR(25) NOT NULL,
	CORREO VARCHAR(60) NOT NULL,
	TELEFONO INT UNSIGNED NOT NULL,
	GENERO ENUM('MASCULINO','FEMENINO','OTRO') NULL,
    FECHA_NACIMIENTO DATE NULL,
    TIPO_USUARIO ENUM('ADMINISTRADOR','CAJERO','CLIENTE') NOT NULL,
    ESTADO ENUM('ACTIVO','INACTIVO') DEFAULT 'ACTIVO' NOT NULL
);
CREATE TABLE MOVIMIENTO (
	ID_MOVIMIENTO SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    FECHA_MOVIMIENTO DATE NOT NULL,
    OBSERVACIONES VARCHAR(150) NULL,
    VALOR_MOVIMIENTO MEDIUMINT UNSIGNED NOT NULL,
    DESCUENTO TINYINT UNSIGNED NULL,
    TIPO_MOVIMIENTO ENUM('COMPRA','VENTA','DEUDA') NOT NULL,
	ESTADO_MOVIMIENTO ENUM('REALIZADO','PENDIENTE') DEFAULT ('REALIZADO') NOT NULL,
    CLIENTE BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (CLIENTE) REFERENCES USUARIO (CEDULA)
    
);
CREATE TABLE PRODUCTO (
	ID_PRODUCTO TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NOMBRE_PRODUCTO VARCHAR(30) NOT NULL,
	DESCRIPCION_PRODUCTO VARCHAR(50) NOT NULL,
	VALOR_UNITARIO SMALLINT UNSIGNED NOT NULL,
    UNIDAD_MEDIDA VARCHAR(10) NOT NULL,
    ESTADO_PRODUCTO ENUM('ACTIVO','INACTIVO') DEFAULT('ACTIVO')
);
CREATE TABLE INVENTARIO(
	ID_ITEM TINYINT UNSIGNED,
    FOREIGN KEY (ID_ITEM) REFERENCES PRODUCTO(ID_PRODUCTO),
    UBICACION VARCHAR(40) NOT NULL,
    CANTIDAD SMALLINT UNSIGNED NOT NULL,
    ESPECIFICACIONES VARCHAR(50) NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    ESTADO ENUM('DISPONIBLE','NO DISPONIBLE') DEFAULT 'DISPONIBLE' NOT NULL
);
CREATE TABLE PROVEEDOR (
	ID_PROVEEDOR TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NOMBRE_PROVEEDOR VARCHAR(40) NOT NULL,
	TELEFONO BIGINT UNSIGNED NOT NULL,
	CORREO VARCHAR(40) NOT NULL,
	DIRECCION VARCHAR(50) NOT NULL,
	ESTADO ENUM('ACTIVO','INACTIVO') DEFAULT 'ACTIVO' NOT NULL
);
CREATE TABLE DETALLE_MOVIMIENTO(
	ID_DETALLE TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    CANTIDAD_MOVIDA SMALLINT UNSIGNED NOT NULL,
    SUBTOTAL SMALLINT UNSIGNED NOT NULL,
    ID_MOVIMIENTO SMALLINT UNSIGNED,
    FOREIGN KEY (ID_MOVIMIENTO) REFERENCES MOVMIENTO (ID_MOVIMIENTO),
    ID_PRODUCTO TINYINT UNSIGNED,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);
CREATE TABLE COMPRA (
	ID_COMPRA SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    FECHA_LLEGADA DATE NOT NULL,
    PROVEEDOR INT UNSIGNED NOT NULL,
    FOREIGN KEY (PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR),
    MOVIMIENTO SMALLINT UNSIGNED NOT NULL,
    FOREIGN KEY (MOVIMIENTO) REFERENCES MOVIMIENTO (ID_MOVIMIENTO),
    PRODUCTO_COMPRADO TINYINT UNSIGNED NOT NULL,
    FOREIGN KEY (PRODUCTO_COMPRADO) REFERENCES PRODUCTO (ID_PRODUCTO)
);
CREATE TABLE DEUDA (
    ID_DEUDA TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	SALDO INT UNSIGNED NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    MOVIMIENTO SMALLINT UNSIGNED NOT NULL,
    FOREIGN KEY (MOVIMIENTO) REFERENCES MOVIMIENTO (ID_MOVIMIENTO),
    PRODUCTO_PENDIENTE TINYINT UNSIGNED NOT NULL,
    FOREIGN KEY (PRODUCTO_PENDIENTE) REFERENCES PRODUCTO (ID_PRODUCTO)
);