CREATE DATABASE CONJUNTO;
USE CONJUNTO;
#Drop database CONJUNTO;
CREATE TABLE USUARIO (
	CEDULA BIGINT UNSIGNED PRIMARY KEY,
	NOMBRE VARCHAR(25) NOT NULL,
	APELLIDO VARCHAR(25) NOT NULL,
	CONTRASENA VARCHAR(25) NOT NULL,
	CORREO VARCHAR(60) NOT NULL,
	TIPO_USUARIO ENUM('ADMINISTRADOR','CAJERO','CLIENTE') NOT NULL,
	ESTADO ENUM('ACTIVO','INACTIVO') DEFAULT 'ACTIVO' NOT NULL,
	TELEFONO INT UNSIGNED NOT NULL,
	GENERO ENUM('MASCULINO','FEMENINO','OTRO') NULL,
    FECHA_NACIMIENTO DATE NULL,
    TIPO_SANGRE VARCHAR(3) NULL
);
CREATE TABLE PROVEEDOR (
	ID_PROVEEDOR INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NOMBRE_PROVEEDOR VARCHAR(40) NOT NULL,
	NUMERO_TELEFONICO BIGINT UNSIGNED NOT NULL,
	CORREO_PROVEEDOR VARCHAR(40) NOT NULL,
	DIRECCION VARCHAR(50) NOT NULL,
	ESTADO ENUM('ACTIVO','INACTIVO') DEFAULT 'ACTIVO' NOT NULL
);
CREATE TABLE MOVIMIENTO (
	ID_MOVIMIENTO SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    VALOR_MOVIMIENTO MEDIUMINT UNSIGNED NOT NULL,
    FECHA_MOVIMIENTO DATE NOT NULL,
    ESTADO_MOVIMIENTO ENUM('REALIZADO','PENDIENTE') DEFAULT ('REALIZADO') NOT NULL,
    DESCUENTO TINYINT UNSIGNED NULL,
    TIPO_MOVIMIENTO ENUM('COMPRA','VENTA','DEUDA') NOT NULL,
	CLIENTE BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (CLIENTE) REFERENCES USUARIO (CEDULA)
);
CREATE TABLE PRODUCTO (
	ID_PRODUCTO TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	NOMBRE_PRODUCTO VARCHAR(30) NOT NULL,
	DESCRIPCION_PRODUCTO VARCHAR(50) NOT NULL,
	CANTIDAD_DISPONIBLE TINYINT UNSIGNED NOT NULL,
	UNIDAD_MEDIDA ENUM('L','Ml','Gal','M','Cm','P','Kg','G','Lb','Mg') NOT NULL,
	ESTADO_PRODUCTO ENUM('DISPONIBLE','NO DISPONIBLE') DEFAULT 'DISPONIBLE' NOT NULL, 
	COSTO_UNITARIO SMALLINT UNSIGNED NOT NULL,
	FECHA_ENTREGA DATE NOT NULL,
	FECHA_VENCIMIENTO DATE NOT NULL,
	REGISTRADO_POR BIGINT UNSIGNED NOT NULL,
	FOREIGN KEY (REGISTRADO_POR) REFERENCES USUARIO (CEDULA)
);
CREATE TABLE DETALLE_VENTA (
	ID_VENTA SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    CANTIDAD_VENDIDA TINYINT UNSIGNED NOT NULL,
    MOVIMIENTO SMALLINT UNSIGNED NOT NULL,
    FOREIGN KEY (MOVIMIENTO) REFERENCES MOVIMIENTO (ID_MOVIMIENTO),
    PRODUCTO_VENDIDO TINYINT UNSIGNED NOT NULL,
    FOREIGN KEY (PRODUCTO_VENDIDO) REFERENCES PRODUCTO (ID_PRODUCTO)
);
CREATE TABLE DETALLE_COMPRA (
	ID_COMPRA SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    CANTIDAD_COMPRADA TINYINT UNSIGNED NOT NULL,
    PROVEEDOR INT UNSIGNED NOT NULL,
    FOREIGN KEY (PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR),
    MOVIMIENTO SMALLINT UNSIGNED NOT NULL,
    FOREIGN KEY (MOVIMIENTO) REFERENCES MOVIMIENTO (ID_MOVIMIENTO),
    PRODUCTO_COMPRADO TINYINT UNSIGNED NOT NULL,
    FOREIGN KEY (PRODUCTO_COMPRADO) REFERENCES PRODUCTO (ID_PRODUCTO)
);
CREATE TABLE DETALLE_DEUDAS (
    ID_DEUDA TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	SALDO INT UNSIGNED NOT NULL,
    CANTIDAD_DEUDA SMALLINT NOT NULL,
    FECHA_VENCIMIENTO DATE NOT NULL,
    MOVIMIENTO SMALLINT UNSIGNED NOT NULL,
    FOREIGN KEY (MOVIMIENTO) REFERENCES MOVIMIENTO (ID_MOVIMIENTO),
    PRODUCTO_PENDIENTE TINYINT UNSIGNED NOT NULL,
    FOREIGN KEY (PRODUCTO_PENDIENTE) REFERENCES PRODUCTO (ID_PRODUCTO)
);