SELECT * FROM USUARIO;
SELECT * FROM PROVEEDOR;
SELECT * FROM PRODUCTO;
SELECT * FROM MOVIMIENTO;
SELECT * FROM DETALLE_COMPRA;
SELECT * FROM DETALLE_VENTA;
SELECT * FROM DETALLE_DEUDAS;

SELECT P.NOMBRE_PRODUCTO, U.NOMBRE AS REGISTRADO_POR_NOMBRE, U.APELLIDO AS REGISTRADO_POR_APELLIDO
FROM PRODUCTO P
JOIN USUARIO U ON P.REGISTRADO_POR = U.CEDULA;

SELECT DC.ID_COMPRA, M.FECHA_MOVIMIENTO, P.NOMBRE_PRODUCTO, DC.CANTIDAD_COMPRADA, M.VALOR_MOVIMIENTO
FROM DETALLE_COMPRA DC
JOIN MOVIMIENTO M ON DC.MOVIMIENTO = M.ID_MOVIMIENTO
JOIN PRODUCTO P ON DC.PRODUCTO_COMPRADO = P.ID_PRODUCTO;

SELECT DV.ID_VENTA, M.VALOR_MOVIMIENTO, DV.CANTIDAD_VENDIDA, P.NOMBRE_PRODUCTO, U.NOMBRE AS CLIENTE
FROM DETALLE_VENTA DV
JOIN MOVIMIENTO M ON DV.MOVIMIENTO = M.ID_MOVIMIENTO
JOIN PRODUCTO P ON DV.PRODUCTO_VENDIDO = P.ID_PRODUCTO
JOIN USUARIO U ON M.CLIENTE = U.CEDULA;

SELECT DD.ID_DEUDA, DD.SALDO, DD.CANTIDAD_DEUDA, DD.FECHA_VENCIMIENTO, P.NOMBRE_PRODUCTO, U.NOMBRE AS CLIENTE
FROM DETALLE_DEUDAS DD
JOIN PRODUCTO P ON DD.PRODUCTO_PENDIENTE = P.ID_PRODUCTO
JOIN MOVIMIENTO M ON DD.MOVIMIENTO = M.ID_MOVIMIENTO
JOIN USUARIO U ON M.CLIENTE = U.CEDULA;

SELECT M.ID_MOVIMIENTO, M.VALOR_MOVIMIENTO, M.TIPO_MOVIMIENTO, M.FECHA_MOVIMIENTO, U.NOMBRE AS CLIENTE
FROM MOVIMIENTO M
JOIN USUARIO U ON M.CLIENTE = U.CEDULA;

SELECT P.NOMBRE_PRODUCTO, PR.NOMBRE_PROVEEDOR, DC.CANTIDAD_COMPRADA
FROM DETALLE_COMPRA DC
JOIN PRODUCTO P ON DC.PRODUCTO_COMPRADO = P.ID_PRODUCTO
JOIN PROVEEDOR PR ON DC.PROVEEDOR = PR.ID_PROVEEDOR;

SELECT M.TIPO_MOVIMIENTO, COUNT(*) AS TOTAL_MOVIMIENTOS, SUM(M.VALOR_MOVIMIENTO) AS VALOR_TOTAL
FROM MOVIMIENTO M
GROUP BY M.TIPO_MOVIMIENTO;

SELECT U.NOMBRE, COUNT(DV.ID_VENTA) AS TOTAL_VENTAS
FROM USUARIO U
JOIN MOVIMIENTO M ON U.CEDULA = M.CLIENTE
JOIN DETALLE_VENTA DV ON M.ID_MOVIMIENTO = DV.MOVIMIENTO
GROUP BY U.CEDULA;
