DELIMITER //
CREATE TRIGGER Desactivar_Producto
AFTER UPDATE ON INVENTARIO
FOR EACH ROW 
BEGIN
	IF NEW.FECHA_VENCIMIENTO IS NOT NULL AND NOW() > NEW.FECHA_VENCIMIENTO THEN
        SET NEW.ESTADO_PRODUCTO = 'NO DISPONIBLE';
    END IF;
END;
DELIMITER ;